
server:
  port: 8001
eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: studentservice
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
instanceId: s1